/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Everything the UI needs to render the configurator and explainers.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_api_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Studio Configuration
         * @description Return the canonical defaults for Ticket 02's migrated static Spot slice.
         */
        get: operations["studio_configuration_api_studio_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/canonical-adaptive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Canonical Adaptive
         * @description Present one deterministic legacy-to-canonical adaptive characterization.
         */
        post: operations["canonical_adaptive_api_studio_canonical_adaptive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/safety-posture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Safety Posture
         * @description Present separate deterministic Ticket 09 safety and lifecycle facts.
         */
        get: operations["safety_posture_api_studio_safety_posture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/operator-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operator Controls
         * @description Present deterministic Ticket 10 control previews and terminal disposal.
         */
        get: operations["operator_controls_api_studio_operator_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/epoch-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Epoch Transition
         * @description Present deterministic Ticket 12 guarded epoch-transition progress.
         */
        get: operations["epoch_transition_api_studio_epoch_transition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/catalogs/binance/eur": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binance Eur Catalog
         * @description Return a dated public Testnet/production EUR intersection.
         */
        get: operations["get_binance_eur_catalog_api_studio_catalogs_binance_eur_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/binance/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Binance Dataset
         * @description Resolve official source identities and sizes before archive download.
         */
        post: operations["preview_binance_dataset_api_studio_datasets_binance_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/binance/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Binance Dataset
         * @description Download and admit only checksum-verified, continuous production history.
         */
        post: operations["import_binance_dataset_api_studio_datasets_binance_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Studio Dataset */
        get: operations["get_studio_dataset_api_studio_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Studio Backtest
         * @description Execute and durably record the typed Studio's migrated Research slice.
         */
        post: operations["create_studio_backtest_api_studio_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests/manifested": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Manifested Studio Backtest
         * @description Replay one admitted production dataset without any network dependency.
         */
        post: operations["create_manifested_studio_backtest_api_studio_backtests_manifested_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Studio Backtest */
        get: operations["get_studio_backtest_api_studio_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grid Preview */
        post: operations["grid_preview_api_grid_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_api_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/grid-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Grid Search */
        post: operations["research_grid_search_api_research_grid_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/walk-forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Walk Forward */
        post: operations["research_walk_forward_api_research_walk_forward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/monte-carlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Monte Carlo */
        post: operations["research_monte_carlo_api_research_monte_carlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/robustness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Robustness */
        post: operations["research_robustness_api_research_robustness_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionLimitsPreview */
        AcquisitionLimitsPreview: {
            /** Max Days */
            max_days: number;
            /** Max Objects */
            max_objects: number;
            /** Max Bytes */
            max_bytes: number;
        };
        /** ArchiveCoverageEvidence */
        ArchiveCoverageEvidence: {
            /**
             * First Date
             * Format: date
             */
            first_date: string;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Intervals */
            intervals: string[];
            /** Known Gap Dates */
            known_gap_dates: string[];
            /** Evidence Urls */
            evidence_urls: string[];
        };
        /** ArchiveSourcePreview */
        ArchiveSourcePreview: {
            /** Date */
            date: string;
            /** Url */
            url: string;
            /** Checksum Url */
            checksum_url: string;
            /** Expected Sha256 */
            expected_sha256: string;
            /** Estimated Bytes */
            estimated_bytes: number;
        };
        /** AuthoritativeInventoryBasisPresentation */
        AuthoritativeInventoryBasisPresentation: {
            /** Basis Id */
            basis_id: string;
            /** Source */
            source: string;
            /** Base Asset */
            base_asset: string;
            quantity: components["schemas"]["ExactValuePresentation"];
            /** Authoritative */
            authoritative: boolean;
            /** Reconciled At */
            reconciled_at: string | null;
        };
        /** BacktestOptions */
        BacktestOptions: {
            /**
             * With Report
             * @default false
             */
            with_report: boolean;
            /**
             * Include Trades
             * @default true
             */
            include_trades: boolean;
        };
        /**
         * BacktestRequest
         * @description A full declarative backtest spec accepted by the API.
         */
        BacktestRequest: {
            /**
             * Symbol
             * @default BTCUSDT
             */
            symbol: string;
            /**
             * Market Type
             * @default spot
             * @enum {string}
             */
            market_type: "spot" | "futures";
            /** Venue */
            venue?: string | null;
            /**
             * Initial Cash
             * @default 10000
             */
            initial_cash: number;
            grid?: components["schemas"]["GridSpec"];
            sizing?: components["schemas"]["SizingSpec"];
            fees?: components["schemas"]["FeesSpec"];
            slippage?: components["schemas"]["SlippageSpec"];
            fill?: components["schemas"]["FillSpec"];
            margin?: components["schemas"]["MarginSpec"];
            bootstrap?: components["schemas"]["BootstrapSpec"];
            constraints?: components["schemas"]["ConstraintsSpec"];
            exchange_rules?: components["schemas"]["ExchangeRulesSpec"];
            data?: components["schemas"]["DataSpec"];
            filter?: components["schemas"]["FilterSpec"];
            /**
             * N Trials
             * @default 1
             */
            n_trials: number;
            /** Periods Per Year */
            periods_per_year?: number | null;
        };
        /** BinanceDatasetPreview */
        BinanceDatasetPreview: {
            /** Preview Id */
            preview_id: string;
            /**
             * Venue
             * @constant
             */
            venue: "binance";
            /**
             * Market
             * @constant
             */
            market: "spot-production-archive";
            /** Symbol */
            symbol: string;
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Estimated Bytes */
            estimated_bytes: number;
            /** Sources */
            sources: components["schemas"]["ArchiveSourcePreview"][];
            limits: components["schemas"]["AcquisitionLimitsPreview"];
            /** Catalog Identity */
            catalog_identity?: string | null;
            /** Symbol Metadata */
            symbol_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** BinanceDatasetRequest */
        BinanceDatasetRequest: {
            /** Catalog Id */
            catalog_id?: string | null;
            /** Symbol */
            symbol: string;
            /**
             * Interval
             * @default 1m
             * @constant
             */
            interval: "1m";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** BinanceEurResearchCatalog */
        BinanceEurResearchCatalog: {
            /** Catalog Id */
            catalog_id: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Quote Asset
             * @constant
             */
            quote_asset: "EUR";
            /** Filters */
            filters: string[];
            /** Sources */
            sources: components["schemas"]["CatalogSourceEvidence"][];
            /** Symbols */
            symbols: components["schemas"]["EurCatalogSymbolEvidence"][];
        };
        /** BootstrapSpec */
        BootstrapSpec: {
            /** Base Fraction */
            base_fraction?: number | null;
            /** Side */
            side?: ("LONG" | "SHORT") | null;
        };
        /** CanonicalActivationGatePresentation */
        CanonicalActivationGatePresentation: {
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "PASSED" | "FAILED" | "BLOCKED";
            /** Reason */
            reason: string;
        };
        /** CanonicalAdaptivePresentation */
        CanonicalAdaptivePresentation: {
            configuration: components["schemas"]["CanonicalConfigurationPresentation"];
            observation: components["schemas"]["CanonicalObservationPresentation"];
            decision: components["schemas"]["CanonicalDecisionPresentation"];
            activation: components["schemas"]["CanonicalInitialActivationPresentation"];
            derived_plan: components["schemas"]["CanonicalDerivedPlanPresentation"] | null;
            legacy_comparison: components["schemas"]["LegacyComparisonPresentation"];
        };
        /** CanonicalAdaptiveRequest */
        CanonicalAdaptiveRequest: {
            /**
             * Symbol
             * @default BTCEUR
             */
            symbol: string;
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /**
             * Trend
             * @default 0.0000
             */
            trend: string;
            /**
             * Volatility
             * @default 0.0100
             */
            volatility: string;
            /**
             * Reference Price
             * @default 100.00
             */
            reference_price: string;
            /**
             * Activation Price
             * @default 100.00
             */
            activation_price: string;
            /** Event Time */
            event_time?: string | null;
            /**
             * Observed Count
             * @default 24
             */
            observed_count: number;
            /**
             * Sequence End
             * @default 24
             */
            sequence_end: number;
            /**
             * Spacing
             * @default GEOMETRIC
             * @enum {string}
             */
            spacing: "GEOMETRIC" | "ARITHMETIC";
            /**
             * Venue Environment
             * @default production
             * @enum {string}
             */
            venue_environment: "production" | "testnet";
            /**
             * Tick Size
             * @default 0.01
             */
            tick_size: string;
            /**
             * Step Size
             * @default 0.00001
             */
            step_size: string;
            /**
             * Minimum Price
             * @default 0.01
             */
            minimum_price: string;
            /** Maximum Price */
            maximum_price?: string | null;
            /**
             * Minimum Quantity
             * @default 0.00010
             */
            minimum_quantity: string;
            /** Maximum Quantity */
            maximum_quantity?: string | null;
            /**
             * Minimum Notional
             * @default 5.00
             */
            minimum_notional: string;
            /** Maximum Notional */
            maximum_notional?: string | null;
            /** Max Open Orders */
            max_open_orders?: number | null;
            /**
             * Foreign Open Orders
             * @default 0
             */
            foreign_open_orders: number;
            /**
             * Symbol Status
             * @default TRADING
             * @enum {string}
             */
            symbol_status: "TRADING" | "SUSPENDED" | "MAINTENANCE" | "DELISTING" | "UNKNOWN";
            /**
             * Spot Trading Allowed
             * @default true
             */
            spot_trading_allowed: boolean;
            /**
             * Limit Maker Supported
             * @default true
             */
            limit_maker_supported: boolean;
            /**
             * Contradictory Rules
             * @default false
             */
            contradictory_rules: boolean;
            /**
             * Bootstrap Complete
             * @default false
             */
            bootstrap_complete: boolean;
            /**
             * Bootstrap Confirmed Base
             * @default 0
             */
            bootstrap_confirmed_base: string;
            /** Bootstrap Evidence Id */
            bootstrap_evidence_id?: string | null;
            /**
             * Complete
             * @default true
             */
            complete: boolean;
            /**
             * Evidence Quality
             * @default ADMITTED
             * @enum {string}
             */
            evidence_quality: "ADMITTED" | "INCOMPLETE" | "STALE" | "GAPPED" | "CONTRADICTORY" | "AMBIGUOUS";
        };
        /** CanonicalAdjacentCyclePresentation */
        CanonicalAdjacentCyclePresentation: {
            /** Buy Rung Index */
            buy_rung_index: number;
            /** Sell Rung Index */
            sell_rung_index: number;
            buy_price: components["schemas"]["ExactValuePresentation"];
            sell_price: components["schemas"]["ExactValuePresentation"];
            cycle_quantity: components["schemas"]["ExactValuePresentation"];
            net_margin: components["schemas"]["ExactValuePresentation"];
            /** Positive */
            positive: boolean;
            /** Reason */
            reason: string;
        };
        /** CanonicalAdmissionAssessmentPresentation */
        CanonicalAdmissionAssessmentPresentation: {
            capital_envelope: components["schemas"]["ExactValuePresentation"];
            still_effective_quote_commitment: components["schemas"]["ExactValuePresentation"];
            proposed_quote_commitment: components["schemas"]["ExactValuePresentation"];
            bootstrap_quote_commitment: components["schemas"]["ExactValuePresentation"];
            total_quote_commitment: components["schemas"]["ExactValuePresentation"];
            fee_reserve: components["schemas"]["ExactValuePresentation"];
            still_effective_inventory_commitment: components["schemas"]["ExactValuePresentation"];
            additional_bootstrap_inventory: components["schemas"]["ExactValuePresentation"];
            maximum_planned_inventory: components["schemas"]["ExactValuePresentation"];
            total_worst_case_inventory: components["schemas"]["ExactValuePresentation"];
            /** Still Effective Order Count */
            still_effective_order_count: number;
            /** Proposed Order Count */
            proposed_order_count: number;
            /** Total Order Count */
            total_order_count: number;
            /** Venue Order Capacity */
            venue_order_capacity: number | null;
            /** Foreign Open Orders */
            foreign_open_orders: number;
        };
        /** CanonicalAdmissionContextPresentation */
        CanonicalAdmissionContextPresentation: {
            still_effective_quote_commitment: components["schemas"]["ExactValuePresentation"];
            still_effective_inventory_commitment: components["schemas"]["ExactValuePresentation"];
            /** Still Effective Order Count */
            still_effective_order_count: number;
        };
        /** CanonicalAllocationPresentation */
        CanonicalAllocationPresentation: {
            quote_allocation: components["schemas"]["ExactValuePresentation"];
            base_allocation: components["schemas"]["ExactValuePresentation"];
            fee_reserve: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalBootstrapEvidencePresentation */
        CanonicalBootstrapEvidencePresentation: {
            /** Complete */
            complete: boolean;
            net_base_confirmed: components["schemas"]["ExactValuePresentation"];
            /** Evidence Id */
            evidence_id: string | null;
        };
        /** CanonicalBootstrapObligationPresentation */
        CanonicalBootstrapObligationPresentation: {
            net_base_required: components["schemas"]["ExactValuePresentation"];
            gross_base_required: components["schemas"]["ExactValuePresentation"];
            fee_base_coverage: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalConfigurationPresentation */
        CanonicalConfigurationPresentation: {
            /** Schema Version */
            schema_version: string;
            /** Configuration Id */
            configuration_id: string;
            /** Policy Id */
            policy_id: string;
            /** Symbol */
            symbol: string;
            /** Base Asset */
            base_asset: string;
            /** Quote Asset */
            quote_asset: string;
            /** Rung Count */
            rung_count: number;
            /**
             * Spacing
             * @enum {string}
             */
            spacing: "ARITHMETIC" | "GEOMETRIC";
            /** Execution Policy Id */
            execution_policy_id: string;
            /** Risk Profile Id */
            risk_profile_id: string;
            /** Operator Inputs */
            operator_inputs: {
                [key: string]: components["schemas"]["ExactValuePresentation"];
            };
        };
        /** CanonicalDecisionPresentation */
        CanonicalDecisionPresentation: {
            /** Decision Id */
            decision_id: string;
            /**
             * Adaptation State
             * @enum {string}
             */
            adaptation_state: "RANGE_NORMAL" | "RANGE_HIGH_VOLATILITY" | "TREND_UP" | "TREND_DOWN" | "UNCERTAIN";
            /**
             * Intent
             * @enum {string}
             */
            intent: "SYMMETRIC" | "WIDEN" | "SHIFT_UP" | "REDUCE_ONLY" | "FROZEN";
            /** Reason */
            reason: string;
            /** Permits Exposure Increasing Buy */
            permits_exposure_increasing_buy: boolean;
            requested_bound_shift: components["schemas"]["ExactValuePresentation"] | null;
        };
        /** CanonicalDerivedPlanPresentation */
        CanonicalDerivedPlanPresentation: {
            /** Schema Version */
            schema_version: string;
            /** Epoch Id */
            epoch_id: string;
            /** Predecessor Epoch Id */
            predecessor_epoch_id: string | null;
            /** Derivation Causation Id */
            derivation_causation_id: string;
            /** Derivation Semantics */
            derivation_semantics: string;
            /** Venue Rule Evidence Id */
            venue_rule_evidence_id: string;
            lower: components["schemas"]["ExactValuePresentation"];
            upper: components["schemas"]["ExactValuePresentation"];
            reference_price: components["schemas"]["ExactValuePresentation"];
            activation_price: components["schemas"]["ExactValuePresentation"];
            /** Unquantized Rungs */
            unquantized_rungs: components["schemas"]["ExactValuePresentation"][];
            /** Quantized Rungs */
            quantized_rungs: components["schemas"]["CanonicalRungPresentation"][];
            /** Obligations */
            obligations: components["schemas"]["CanonicalObligationPresentation"][];
            allocation_assumptions: components["schemas"]["CanonicalAllocationPresentation"];
            maximum_planned_inventory: components["schemas"]["ExactValuePresentation"] | null;
            bootstrap_obligation: components["schemas"]["CanonicalBootstrapObligationPresentation"] | null;
        };
        /** CanonicalInitialActivationPresentation */
        CanonicalInitialActivationPresentation: {
            /** Schema Version */
            schema_version: string;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "REJECTED" | "BOOTSTRAPPING" | "ACTIVE";
            /** Replay Fingerprint */
            replay_fingerprint: string;
            /** Ladder Placement Allowed */
            ladder_placement_allowed: boolean;
            /** Activation Pending */
            activation_pending: boolean;
            /** Automatically Armed */
            automatically_armed: boolean;
            derived_width: components["schemas"]["ExactValuePresentation"] | null;
            /** Gates */
            gates: components["schemas"]["CanonicalActivationGatePresentation"][];
            bootstrap_evidence: components["schemas"]["CanonicalBootstrapEvidencePresentation"];
            admission_context: components["schemas"]["CanonicalAdmissionContextPresentation"];
            admission_assessment: components["schemas"]["CanonicalAdmissionAssessmentPresentation"] | null;
            /** Adjacent Cycle Economics */
            adjacent_cycle_economics: components["schemas"]["CanonicalAdjacentCyclePresentation"][];
            principal_feasibility: components["schemas"]["CanonicalPrincipalFeasibilityPresentation"];
            post_only_retry_policy: components["schemas"]["CanonicalPostOnlyRetryPolicyPresentation"];
            rule_fee_contract: components["schemas"]["CanonicalRuleFeeContractPresentation"];
        };
        /** CanonicalObligationPresentation */
        CanonicalObligationPresentation: {
            /** Rung Index */
            rung_index: number;
            /**
             * Role
             * @enum {string}
             */
            role: "BUY" | "SELL";
            fixed_quote_principal: components["schemas"]["ExactValuePresentation"];
            base_quantity: components["schemas"]["ExactValuePresentation"] | null;
        };
        /** CanonicalObservationPresentation */
        CanonicalObservationPresentation: {
            /** Schema Version */
            schema_version: string;
            /** Observation Id */
            observation_id: string;
            /** Event Id */
            event_id: string;
            /** Source System */
            source_system: string;
            /** Source Stream */
            source_stream: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Complete */
            complete: boolean;
            /** Quality */
            quality: string;
            /** Confirmation Ids */
            confirmation_ids: string[];
            /** Prior Decision Id */
            prior_decision_id: string | null;
            trend: components["schemas"]["ExactValuePresentation"];
            volatility: components["schemas"]["ExactValuePresentation"];
            reference_price: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalPostOnlyRetryPolicyPresentation */
        CanonicalPostOnlyRetryPolicyPresentation: {
            /** Schema Version */
            schema_version: string;
            /**
             * Order Type
             * @constant
             */
            order_type: "LIMIT_MAKER";
            /** Max Attempts */
            max_attempts: number;
            /** Retry Delays */
            retry_delays: components["schemas"]["ExactValuePresentation"][];
            max_price_displacement_ratio: components["schemas"]["ExactValuePresentation"];
            max_adjacent_gap_fraction: components["schemas"]["ExactValuePresentation"];
            /**
             * Exhaustion Posture
             * @constant
             */
            exhaustion_posture: "REDUCE_ONLY";
        };
        /** CanonicalPrincipalFeasibilityPointPresentation */
        CanonicalPrincipalFeasibilityPointPresentation: {
            principal: components["schemas"]["ExactValuePresentation"];
            /** Feasible */
            feasible: boolean;
            /** Reasons */
            reasons: string[];
        };
        /** CanonicalPrincipalFeasibilityPresentation */
        CanonicalPrincipalFeasibilityPresentation: {
            /** Schema Version */
            schema_version: string;
            /** Points */
            points: components["schemas"]["CanonicalPrincipalFeasibilityPointPresentation"][];
        };
        /** CanonicalRuleFeeContractPresentation */
        CanonicalRuleFeeContractPresentation: {
            /** Schema Version */
            schema_version: string;
            /** Contract Id */
            contract_id: string;
            /** Venue Rule Evidence Id */
            venue_rule_evidence_id: string;
            maker_fee: components["schemas"]["ExactValuePresentation"];
            taker_fee: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalRungPresentation */
        CanonicalRungPresentation: {
            /** Index */
            index: number;
            price: components["schemas"]["ExactValuePresentation"];
            /**
             * Role
             * @enum {string}
             */
            role: "BUY" | "SELL" | "INACTIVE";
        };
        /** CatalogSourceEvidence */
        CatalogSourceEvidence: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "production" | "testnet";
            /** Url */
            url: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** ConstraintsSpec */
        ConstraintsSpec: {
            /** Max Base Inventory */
            max_base_inventory?: number | null;
            /** Max Gross Exposure Frac */
            max_gross_exposure_frac?: number | null;
            /** Max Open Orders */
            max_open_orders?: number | null;
            /** Min Order Qty */
            min_order_qty?: number | null;
            /** Min Notional */
            min_notional?: number | null;
        };
        /** DataSpec */
        DataSpec: {
            /** Kind */
            kind?: ("synthetic" | "dataframe" | "binance" | "csv" | "manifested_parquet") | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** N */
            n?: number | null;
            /** Start Price */
            start_price?: number | null;
            /** Seed */
            seed?: number | null;
            /** Sigma */
            sigma?: number | null;
            /** Regime */
            regime?: ("range" | "trend" | "random") | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
            /** Records */
            records?: {
                [key: string]: unknown;
            }[] | null;
            /** Symbol */
            symbol?: string | null;
            /** Interval */
            interval?: string | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Max Candles */
            max_candles?: number | null;
            /** Path */
            path?: string | null;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Dataset Id */
            dataset_id: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Schema Version */
            schema_version: string;
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
            /**
             * Venue
             * @constant
             */
            venue: "binance";
            /**
             * Market
             * @constant
             */
            market: "spot";
            /**
             * History Environment
             * @constant
             */
            history_environment: "production";
            /** Source Provider */
            source_provider: string;
            /** Catalog Identity */
            catalog_identity?: string | null;
            /** Symbol Metadata */
            symbol_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Symbol */
            symbol: string;
            /**
             * Event Kind
             * @constant
             */
            event_kind: "kline";
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            /** Requested Range */
            requested_range: {
                [key: string]: string;
            };
            /** Coverage */
            coverage: {
                [key: string]: string;
            };
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Timestamp */
            timestamp: {
                [key: string]: unknown;
            };
            quality: components["schemas"]["DatasetQuality"];
            normalization: components["schemas"]["DatasetNormalization"];
            /** Venue Rule Snapshot Id */
            venue_rule_snapshot_id: string | null;
            /** Fee Snapshot Id */
            fee_snapshot_id: string | null;
        };
        /** DatasetNormalization */
        DatasetNormalization: {
            /** Identity */
            identity: string;
            /**
             * Format
             * @constant
             */
            format: "parquet";
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Rows */
            rows: number;
            /** Schema */
            schema: components["schemas"]["ParquetField"][];
            /** Candle Sequence Sha256 */
            candle_sequence_sha256: string;
            /** Ordering */
            ordering: string[];
            /** Parent Dataset Id */
            parent_dataset_id: string | null;
            /** Resampling Rule */
            resampling_rule: string | null;
        };
        /** DatasetQuality */
        DatasetQuality: {
            /** Rows */
            rows: number;
            /** Gaps */
            gaps: number;
            /** Duplicates */
            duplicates: number;
            /** Out Of Order */
            out_of_order: number;
            /** Invalid Records */
            invalid_records: number;
        };
        /** EpochTransitionActivationPresentation */
        EpochTransitionActivationPresentation: {
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "REJECTED" | "BOOTSTRAPPING" | "ACTIVE";
            /** Replay Fingerprint */
            replay_fingerprint: string;
            /** Ladder Placement Allowed */
            ladder_placement_allowed: boolean;
            /** Bootstrap Required */
            bootstrap_required: boolean;
            admission_context: components["schemas"]["CanonicalAdmissionContextPresentation"];
            admission_assessment: components["schemas"]["EpochTransitionAdmissionAssessmentPresentation"] | null;
            /** Gates */
            gates: components["schemas"]["CanonicalActivationGatePresentation"][];
        };
        /** EpochTransitionAdmissionAssessmentPresentation */
        EpochTransitionAdmissionAssessmentPresentation: {
            capital_envelope: components["schemas"]["ExactValuePresentation"];
            total_quote_commitment: components["schemas"]["ExactValuePresentation"];
            bootstrap_quote_commitment: components["schemas"]["ExactValuePresentation"];
            fee_reserve: components["schemas"]["ExactValuePresentation"];
            maximum_planned_inventory: components["schemas"]["ExactValuePresentation"];
            total_worst_case_inventory: components["schemas"]["ExactValuePresentation"];
            /** Total Order Count */
            total_order_count: number;
            /** Venue Order Capacity */
            venue_order_capacity: number | null;
        };
        /** EpochTransitionEvidencePresentation */
        EpochTransitionEvidencePresentation: {
            /** Observation Id */
            observation_id: string;
            /** Decision Id */
            decision_id: string;
            /**
             * Adaptation State
             * @enum {string}
             */
            adaptation_state: "RANGE_NORMAL" | "RANGE_HIGH_VOLATILITY" | "TREND_UP" | "TREND_DOWN" | "UNCERTAIN";
            /**
             * Intent
             * @enum {string}
             */
            intent: "SYMMETRIC" | "WIDEN" | "SHIFT_UP" | "REDUCE_ONLY" | "FROZEN";
            /** Reason */
            reason: string;
        };
        /** EpochTransitionGatePresentation */
        EpochTransitionGatePresentation: {
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "PASSED" | "FAILED" | "NOT_APPLICABLE";
            /** Reason */
            reason: string;
        };
        /** EpochTransitionLateFillPresentation */
        EpochTransitionLateFillPresentation: {
            /** Fill Id */
            fill_id: string;
            /** Order Id */
            order_id: string;
            /** Original Epoch Id */
            original_epoch_id: string;
            /** Posting Epoch Id */
            posting_epoch_id: string;
        };
        /** EpochTransitionOrderPresentation */
        EpochTransitionOrderPresentation: {
            /** Order Id */
            order_id: string;
            /** Epoch Id */
            epoch_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /**
             * State
             * @enum {string}
             */
            state: "OPEN" | "CANCEL_PENDING" | "CANCELLED" | "FILLED" | "UNKNOWN";
            /** Exposure Increasing */
            exposure_increasing: boolean;
            /** Inventory Reducing */
            inventory_reducing: boolean;
            /** Terminal Proven */
            terminal_proven: boolean;
            /** Outcome Unknown */
            outcome_unknown: boolean;
        };
        /** EpochTransitionPermissionsPresentation */
        EpochTransitionPermissionsPresentation: {
            /** Placement Allowed */
            placement_allowed: boolean;
            /** Replacement Allowed */
            replacement_allowed: boolean;
            /** Cancellation Allowed */
            cancellation_allowed: boolean;
            /** Reconciliation Allowed */
            reconciliation_allowed: boolean;
            /** Inventory Reduction Allowed */
            inventory_reduction_allowed: boolean;
        };
        /** EpochTransitionPresentation */
        EpochTransitionPresentation: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "epoch-transition-evaluation/v1";
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Fingerprint */
            fingerprint: string;
            /** Active Epoch Id */
            active_epoch_id: string;
            /** Proposed Epoch Id */
            proposed_epoch_id: string | null;
            /**
             * Phase
             * @enum {string}
             */
            phase: "ACTIVE" | "CHANGE_CONFIRMED" | "TRANSITION_REQUESTED" | "OLD_EXPOSURE_BLOCKED" | "CANCELLING" | "RECONCILING" | "DERIVING" | "VALIDATING" | "BOOTSTRAPPING" | "ACTIVATING";
            /**
             * Posture
             * @enum {string}
             */
            posture: "NORMAL" | "REDUCE_ONLY" | "TERMINAL_LIQUIDATION" | "FROZEN" | "CLOSED";
            evidence: components["schemas"]["EpochTransitionEvidencePresentation"];
            /** Refusal Reason */
            refusal_reason: string | null;
            /** Crash Safe */
            crash_safe: boolean;
            /** Restart Boundaries */
            restart_boundaries: ("CHANGE_CONFIRMED" | "TRANSITION_REQUESTED" | "OLD_EXPOSURE_BLOCKED" | "CANCELLING" | "RECONCILING" | "DERIVING" | "VALIDATING" | "BOOTSTRAPPING" | "ACTIVATING" | "ACTIVE")[];
            /** Gates */
            gates: components["schemas"]["EpochTransitionGatePresentation"][];
            /** Progress */
            progress: components["schemas"]["EpochTransitionProgressPresentation"][];
            permissions: components["schemas"]["EpochTransitionPermissionsPresentation"];
            inventory_basis: components["schemas"]["AuthoritativeInventoryBasisPresentation"];
            /** Old Orders */
            old_orders: components["schemas"]["EpochTransitionOrderPresentation"][];
            /** Late Fill Postings */
            late_fill_postings: components["schemas"]["EpochTransitionLateFillPresentation"][];
            replacement_activation: components["schemas"]["EpochTransitionActivationPresentation"] | null;
        };
        /** EpochTransitionProgressPresentation */
        EpochTransitionProgressPresentation: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "CHANGE_CONFIRMED" | "TRANSITION_REQUESTED" | "OLD_EXPOSURE_BLOCKED" | "CANCELLING" | "RECONCILING" | "DERIVING" | "VALIDATING" | "BOOTSTRAPPING" | "ACTIVATING" | "ACTIVE";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CURRENT" | "COMPLETED" | "SKIPPED" | "FAILED";
            /** Reason */
            reason: string;
        };
        /** EurCatalogSymbolEvidence */
        EurCatalogSymbolEvidence: {
            /** Symbol */
            symbol: string;
            /** Base Asset */
            base_asset: string;
            /**
             * Quote Asset
             * @constant
             */
            quote_asset: "EUR";
            /**
             * Status
             * @constant
             */
            status: "TRADING";
            /** Exchange Filters */
            exchange_filters: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            coverage: components["schemas"]["ArchiveCoverageEvidence"];
            liquidity: components["schemas"]["LiquiditySelectionEvidence"];
            /** Liquidity Rank */
            liquidity_rank: number;
        };
        /** ExactValuePresentation */
        ExactValuePresentation: {
            /** Kind */
            kind: string;
            /** Value */
            value: string;
        };
        /** ExchangeRulesSpec */
        ExchangeRulesSpec: {
            /** Enabled */
            enabled?: boolean | null;
            /** Tick Size */
            tick_size?: number | null;
            /** Step Size */
            step_size?: number | null;
            /** Min Qty */
            min_qty?: number | null;
            /** Min Notional */
            min_notional?: number | null;
        };
        /** FeesSpec */
        FeesSpec: {
            /** Maker */
            maker?: number | null;
            /** Taker */
            taker?: number | null;
        };
        /** FillSpec */
        FillSpec: {
            /** Mode */
            mode?: ("optimistic" | "conservative") | null;
            /** Fill On Touch */
            fill_on_touch?: boolean | null;
            /** Fill Gaps At Open */
            fill_gaps_at_open?: boolean | null;
            /** Participation */
            participation?: number | null;
        };
        /** FilterSpec */
        FilterSpec: {
            /** Kind */
            kind?: ("none" | "trend" | "regime" | "rsi") | null;
            /** Adx Threshold */
            adx_threshold?: number | null;
            /** Oversold */
            oversold?: number | null;
            /** Overbought */
            overbought?: number | null;
        };
        /**
         * GridPreviewBody
         * @description Lightweight request to compute grid rung prices for the live preview.
         */
        GridPreviewBody: {
            spec?: components["schemas"]["BacktestRequest"];
        };
        /** GridSearchBody */
        GridSearchBody: {
            base?: components["schemas"]["BacktestRequest"];
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
            /**
             * Objective
             * @default deflated_sharpe
             */
            objective: string;
            /**
             * Maximize
             * @default true
             */
            maximize: boolean;
            /** Top K */
            top_k?: number | null;
        };
        /** GridSpec */
        GridSpec: {
            /** Levels */
            levels?: number | null;
            /** Lower */
            lower?: number | null;
            /** Upper */
            upper?: number | null;
            /** Spacing */
            spacing?: ("arithmetic" | "geometric" | "atr") | null;
            /** Direction */
            direction?: ("neutral" | "long" | "short") | null;
            /** Adaptive */
            adaptive?: boolean | null;
            /** Lookback */
            lookback?: number | null;
            /** Atr Period */
            atr_period?: number | null;
            /** Atr Mult */
            atr_mult?: number | null;
            /** Recenter Drift Frac */
            recenter_drift_frac?: number | null;
            /** Take Profit Frac */
            take_profit_frac?: number | null;
            /** Stop Loss Frac */
            stop_loss_frac?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportDatasetBody */
        ImportDatasetBody: {
            /** Preview Id */
            preview_id: string;
        };
        /** LegacyComparisonPresentation */
        LegacyComparisonPresentation: {
            /** Bounded Bars */
            bounded_bars: number;
            /** Legacy Adaptive */
            legacy_adaptive: boolean;
            /** Legacy Spacing */
            legacy_spacing: string;
            /** Effective Atr Multiplier */
            effective_atr_multiplier: string;
            /** Cancelled Orders */
            cancelled_orders: number;
            /** Semantic Differences */
            semantic_differences: string[];
        };
        /** LiquiditySelectionEvidence */
        LiquiditySelectionEvidence: {
            /** Observed Days */
            observed_days: number;
            /**
             * Observed Start Date
             * Format: date
             */
            observed_start_date: string;
            /**
             * Observed End Date
             * Format: date
             */
            observed_end_date: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Kline Source Url */
            kline_source_url: string;
            /** Kline Payload Sha256 */
            kline_payload_sha256: string;
            /** Ticker Source Url */
            ticker_source_url: string;
            /** Ticker Payload Sha256 */
            ticker_payload_sha256: string;
            /** Median Daily Quote Volume */
            median_daily_quote_volume: string;
            /** Median Daily Trade Count */
            median_daily_trade_count: string;
            /** Annualized Realized Volatility */
            annualized_realized_volatility: string;
            /** Current Spread Bps */
            current_spread_bps: string;
            /** Current Trade Count */
            current_trade_count: number;
        };
        /** ManifestedBacktestBody */
        ManifestedBacktestBody: {
            /** Dataset Id */
            dataset_id: string;
            spec: components["schemas"]["BacktestRequest"];
            options?: components["schemas"]["BacktestOptions"];
        };
        /** MarginSpec */
        MarginSpec: {
            /** Leverage */
            leverage?: number | null;
            /** Maintenance Margin Frac */
            maintenance_margin_frac?: number | null;
            /** Liquidation Fee Frac */
            liquidation_fee_frac?: number | null;
            /** Allow Short */
            allow_short?: boolean | null;
        };
        /** MonteCarloBody */
        MonteCarloBody: {
            base?: components["schemas"]["BacktestRequest"];
            /**
             * Method
             * @default trades
             * @enum {string}
             */
            method: "trades" | "returns";
            /**
             * N Sims
             * @default 2000
             */
            n_sims: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** OperatorCommandPreviewPresentation */
        OperatorCommandPreviewPresentation: {
            /**
             * Action
             * @enum {string}
             */
            action: "PAUSE" | "RESUME" | "OPERATOR_STOP" | "EMERGENCY_STOP";
            /**
             * Availability
             * @enum {string}
             */
            availability: "IMMEDIATE" | "PREVIEW_REQUIRED" | "BLOCKED" | "LATCHED";
            /** Confirmation Required */
            confirmation_required: boolean;
            /** Environment Bound */
            environment_bound: boolean;
            /** Idempotent */
            idempotent: boolean;
            /** Preempts Pending Activation */
            preempts_pending_activation: boolean;
            /** Blocks New Epoch Placement */
            blocks_new_epoch_placement: boolean;
            /** Admission Order Preserved */
            admission_order_preserved: boolean;
            /** Active Epoch Id */
            active_epoch_id: string;
            /** Proposed Epoch Id */
            proposed_epoch_id: string | null;
            /** Transition State */
            transition_state: string;
            /**
             * Posture
             * @enum {string}
             */
            posture: "NORMAL" | "REDUCE_ONLY" | "TERMINAL_LIQUIDATION" | "FROZEN" | "CLOSED";
            /** Inventory Basis Id */
            inventory_basis_id: string;
            /** Cancel Obligation Ids */
            cancel_obligation_ids: string[];
            /** Retained Obligation Ids */
            retained_obligation_ids: string[];
            /** Late Fill Ids */
            late_fill_ids: string[];
            /** Gates */
            gates: components["schemas"]["OperatorPreviewGatePresentation"][];
            /** Reason Codes */
            reason_codes: string[];
            /** Available Dispositions */
            available_dispositions: ("RETAIN_HOLDING" | "DISPOSE")[];
            /** Selected Disposition */
            selected_disposition: ("RETAIN_HOLDING" | "DISPOSE") | null;
        };
        /** OperatorControlsPresentation */
        OperatorControlsPresentation: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "operator-controls-presentation/v1";
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Fingerprint */
            fingerprint: string;
            projection: components["schemas"]["OperatorProjectionPresentation"];
            inventory_basis: components["schemas"]["AuthoritativeInventoryBasisPresentation"];
            pause: components["schemas"]["OperatorCommandPreviewPresentation"];
            resume: components["schemas"]["OperatorCommandPreviewPresentation"];
            operator_stop: components["schemas"]["OperatorCommandPreviewPresentation"];
            emergency_stop: components["schemas"]["OperatorCommandPreviewPresentation"];
            terminal: components["schemas"]["TerminalDisposalPresentation"];
        };
        /** OperatorPreviewGatePresentation */
        OperatorPreviewGatePresentation: {
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "PASSED" | "FAILED";
            /** Reason */
            reason: string;
        };
        /** OperatorProjectionPresentation */
        OperatorProjectionPresentation: {
            /** Active Epoch Id */
            active_epoch_id: string;
            /** Proposed Epoch Id */
            proposed_epoch_id: string | null;
            /** Transition State */
            transition_state: string;
            /**
             * Posture
             * @enum {string}
             */
            posture: "NORMAL" | "REDUCE_ONLY" | "TERMINAL_LIQUIDATION" | "FROZEN" | "CLOSED";
        };
        /** ParquetField */
        ParquetField: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
        };
        /** ProductionDatasetProvenance */
        ProductionDatasetProvenance: {
            /** Dataset Id */
            dataset_id: string;
            /** Manifest Identity */
            manifest_identity: string;
            /** Source Provider */
            source_provider: string;
            /**
             * History Environment
             * @constant
             */
            history_environment: "production";
            /**
             * Testnet History Used
             * @constant
             */
            testnet_history_used: false;
            /** Symbol */
            symbol: string;
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            /**
             * Requested Start
             * Format: date-time
             */
            requested_start: string;
            /**
             * Requested End
             * Format: date-time
             */
            requested_end: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Urls */
            source_urls: string[];
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Candle Sequence Sha256 */
            candle_sequence_sha256: string;
            /** Backtest Fingerprint */
            backtest_fingerprint: string;
            /** Catalog Identity */
            catalog_identity?: string | null;
            /** Quote Asset */
            quote_asset?: string | null;
        };
        /** RobustnessBody */
        RobustnessBody: {
            base?: components["schemas"]["BacktestRequest"];
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
            /**
             * N Splits
             * @default 3
             */
            n_splits: number;
            /**
             * Mc Sims
             * @default 800
             */
            mc_sims: number;
        };
        /** RunBacktestBody */
        RunBacktestBody: {
            spec?: components["schemas"]["BacktestRequest"];
            options?: components["schemas"]["BacktestOptions"];
        };
        /** SafetyCapitalPresentation */
        SafetyCapitalPresentation: {
            /** Allocation Fingerprint */
            allocation_fingerprint: string;
            /** Epoch Id */
            epoch_id: string;
            capital_envelope: components["schemas"]["ExactValuePresentation"];
            committed_principal: components["schemas"]["ExactValuePresentation"];
            fee_reserve: components["schemas"]["ExactValuePresentation"];
            maximum_planned_inventory: components["schemas"]["ExactValuePresentation"];
        };
        /** SafetyFactPresentation */
        SafetyFactPresentation: {
            /**
             * Posture
             * @enum {string}
             */
            posture: "NORMAL" | "REDUCE_ONLY" | "TERMINAL_LIQUIDATION" | "FROZEN" | "CLOSED";
            /** Reason Codes */
            reason_codes: string[];
            /** Loss Warning */
            loss_warning: boolean;
            /** Daily Loss Latched */
            daily_loss_latched: boolean;
            /** Run Drawdown Latched */
            run_drawdown_latched: boolean;
            /** Global Stop Latched */
            global_stop_latched: boolean;
            /** Allowed Command Classes */
            allowed_command_classes: ("EXPOSURE_INCREASING" | "INVENTORY_REDUCING" | "PLACEMENT" | "REPLACEMENT" | "CANCELLATION" | "RECONCILIATION" | "EVIDENCE_GATHERING")[];
            /** Placement Allowed */
            placement_allowed: boolean;
            /** Replacement Allowed */
            replacement_allowed: boolean;
            /** Downward Bound Shift Allowed */
            downward_bound_shift_allowed: boolean;
            /** Fixed Quote Sizing Increase Allowed */
            fixed_quote_sizing_increase_allowed: boolean;
            clock_offset: components["schemas"]["ExactValuePresentation"];
            scheduling_delay: components["schemas"]["ExactValuePresentation"];
            round_trip_latency: components["schemas"]["ExactValuePresentation"];
        };
        /** SafetyFreshnessPresentation */
        SafetyFreshnessPresentation: {
            /**
             * Evidence Class
             * @enum {string}
             */
            evidence_class: "VALUATION" | "STRATEGY_INPUT" | "PRIVATE_STREAM" | "CONTROL_PATH" | "CLOCK";
            /**
             * Condition
             * @enum {string}
             */
            condition: "HEALTHY" | "MISSING" | "STALE" | "GAPPED" | "DISCONNECTED" | "UNAVAILABLE" | "REJECTED";
            /** Observed At */
            observed_at: string | null;
            /** Evidence Id */
            evidence_id: string;
        };
        /** SafetyLifecyclePresentation */
        SafetyLifecyclePresentation: {
            /** Grid Lifecycle */
            grid_lifecycle: string;
            /**
             * Adaptation State
             * @enum {string}
             */
            adaptation_state: "RANGE_NORMAL" | "RANGE_HIGH_VOLATILITY" | "TREND_UP" | "TREND_DOWN" | "UNCERTAIN";
            /** Epoch Transition State */
            epoch_transition_state: string;
            /** Runtime Lifecycle */
            runtime_lifecycle: string;
            /** Reconciliation State */
            reconciliation_state: string;
        };
        /** SafetyPosturePresentation */
        SafetyPosturePresentation: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "safety-posture-presentation/v1";
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Fingerprint */
            fingerprint: string;
            capital: components["schemas"]["SafetyCapitalPresentation"];
            lifecycle: components["schemas"]["SafetyLifecyclePresentation"];
            safety: components["schemas"]["SafetyFactPresentation"];
            /** Freshness */
            freshness: components["schemas"]["SafetyFreshnessPresentation"][];
            venue: components["schemas"]["SafetyVenuePresentation"];
        };
        /** SafetyVenuePresentation */
        SafetyVenuePresentation: {
            /**
             * Condition
             * @enum {string}
             */
            condition: "TRADING" | "SUSPENDED" | "MAINTENANCE" | "DELISTING";
            /** Evidence Id */
            evidence_id: string;
            /** Source */
            source: string;
            /** Wind Down Deadline */
            wind_down_deadline: string | null;
        };
        /** SizingSpec */
        SizingSpec: {
            /** Mode */
            mode?: ("fixed_quote" | "fixed_base" | "percent_equity" | "martingale") | null;
            /** Value */
            value?: number | null;
            /** Martingale Factor */
            martingale_factor?: number | null;
            /** Max Martingale Steps */
            max_martingale_steps?: number | null;
        };
        /** SlippageSpec */
        SlippageSpec: {
            /** Spread Frac */
            spread_frac?: number | null;
            /** Impact Frac */
            impact_frac?: number | null;
        };
        /** StudioBacktestResult */
        StudioBacktestResult: {
            /** Symbol */
            symbol: string;
            /** Bars */
            bars: number;
            /** Initial Cash */
            initial_cash: number;
            /** Final Equity */
            final_equity: number;
            /** Fees Paid */
            fees_paid: number;
            metrics: components["schemas"]["StudioMetrics"];
            verdict: components["schemas"]["StudioVerdict"];
            /** Trades */
            trades: {
                [key: string]: unknown;
            }[];
            simulation: components["schemas"]["StudioSimulationPresentation"];
        } & {
            [key: string]: unknown;
        };
        /** StudioBacktestRun */
        StudioBacktestRun: {
            /** Id */
            id: string;
            /**
             * Status
             * @constant
             */
            status: "completed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Specification */
            specification: {
                [key: string]: unknown;
            };
            primary_result: components["schemas"]["StudioPrimaryResult"];
            result: components["schemas"]["StudioBacktestResult"];
            provenance?: components["schemas"]["ProductionDatasetProvenance"] | null;
        };
        /** StudioConfiguration */
        StudioConfiguration: {
            default_spec: components["schemas"]["BacktestRequest"];
            /** Spacing */
            spacing: ("geometric" | "arithmetic")[];
            /** Data Regimes */
            data_regimes: ("range" | "trend" | "random")[];
        };
        /** StudioMetrics */
        StudioMetrics: {
            /** Total Return */
            total_return: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** N Trades */
            n_trades: number;
            /** Win Rate */
            win_rate: number | null;
        } & {
            [key: string]: unknown;
        };
        /** StudioPrimaryResult */
        StudioPrimaryResult: {
            /** Net Return */
            net_return: number;
            /** Final Equity */
            final_equity: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Completed Trades */
            completed_trades: number;
            /** Fees Paid */
            fees_paid: number;
            /** Verdict */
            verdict: string;
        };
        /** StudioSimulationPresentation */
        StudioSimulationPresentation: {
            /**
             * Mode
             * @constant
             */
            mode: "candle";
            /** Canonical Core */
            canonical_core: boolean;
            /** Venue Execution Proof */
            venue_execution_proof: boolean;
            /** Limitations */
            limitations: string[];
        };
        /** StudioVerdict */
        StudioVerdict: {
            /** Label */
            label: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "good" | "warn" | "bad";
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
        };
        /** TerminalDisposalPresentation */
        TerminalDisposalPresentation: {
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "NONE" | "OPERATOR_EMERGENCY" | "TERMINAL_LOSS";
            /**
             * State
             * @enum {string}
             */
            state: "NONE" | "AWAITING_AUTHORITATIVE_INVENTORY" | "DISPOSING" | "DISPOSED" | "RETAINED";
            /** Global Stop Latched */
            global_stop_latched: boolean;
            /** Operator Emergency Latched */
            operator_emergency_latched: boolean;
            /** Automatic Liquidation */
            automatic_liquidation: boolean;
            /** Preempts Pending Activation */
            preempts_pending_activation: boolean;
            /** Admission Order Preserved */
            admission_order_preserved: boolean;
            /** Active Epoch Id */
            active_epoch_id: string;
            /** Proposed Epoch Id */
            proposed_epoch_id: string | null;
            /** Transition State */
            transition_state: string;
            /**
             * Posture
             * @enum {string}
             */
            posture: "NORMAL" | "REDUCE_ONLY" | "TERMINAL_LIQUIDATION" | "FROZEN" | "CLOSED";
            /** Inventory Basis Id */
            inventory_basis_id: string;
            /** Waves */
            waves: components["schemas"]["TerminalDisposalWavePresentation"][];
            /** Golden Replay Cases */
            golden_replay_cases: components["schemas"]["TerminalGoldenReplayPresentation"][];
        };
        /** TerminalDisposalWavePresentation */
        TerminalDisposalWavePresentation: {
            /** Wave */
            wave: number;
            /**
             * Order Type
             * @constant
             */
            order_type: "IOC";
            quantity_limit: components["schemas"]["ExactValuePresentation"];
            notional_limit: components["schemas"]["ExactValuePresentation"];
            max_depth_age: components["schemas"]["ExactValuePresentation"];
            price_band_bps: components["schemas"]["ExactValuePresentation"];
            /** Attempt Limit */
            attempt_limit: number;
            elapsed_time_limit: components["schemas"]["ExactValuePresentation"];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "PARTIAL" | "REJECTED" | "UNKNOWN" | "EXHAUSTED" | "RESIDUAL_RETAINED" | "COMPLETED";
            /** Reconciled Before Next Wave */
            reconciled_before_next_wave: boolean;
            authoritative_inventory_after_wave: components["schemas"]["ExactValuePresentation"];
        };
        /** TerminalGoldenReplayPresentation */
        TerminalGoldenReplayPresentation: {
            /**
             * Case Name
             * @enum {string}
             */
            case_name: "GAP_THROUGH" | "PARTIAL_DISPOSAL" | "REJECTION" | "UNKNOWN_OUTCOME" | "ATTEMPT_EXHAUSTION" | "RESIDUAL_HOLDINGS";
            /** Outcome */
            outcome: string;
            /** Replay Fingerprint */
            replay_fingerprint: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalkForwardBody */
        WalkForwardBody: {
            base?: components["schemas"]["BacktestRequest"];
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
            /**
             * N Splits
             * @default 4
             */
            n_splits: number;
            /**
             * Objective
             * @default deflated_sharpe
             */
            objective: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    backtest_api_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    studio_configuration_api_studio_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioConfiguration"];
                };
            };
        };
    };
    canonical_adaptive_api_studio_canonical_adaptive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanonicalAdaptiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalAdaptivePresentation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    safety_posture_api_studio_safety_posture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyPosturePresentation"];
                };
            };
        };
    };
    operator_controls_api_studio_operator_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorControlsPresentation"];
                };
            };
        };
    };
    epoch_transition_api_studio_epoch_transition_get: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpochTransitionPresentation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binance_eur_catalog_api_studio_catalogs_binance_eur_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceEurResearchCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_binance_dataset_api_studio_datasets_binance_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinanceDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceDatasetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_binance_dataset_api_studio_datasets_binance_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportDatasetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_studio_dataset_api_studio_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_studio_backtest_api_studio_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manifested_studio_backtest_api_studio_backtests_manifested_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestedBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_studio_backtest_api_studio_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grid_preview_api_grid_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridPreviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_grid_search_api_research_grid_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridSearchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_walk_forward_api_research_walk_forward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalkForwardBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_monte_carlo_api_research_monte_carlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_robustness_api_research_robustness_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobustnessBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
