/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_api_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grid Preview */
        post: operations["grid_preview_api_grid_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Everything the UI needs to render the configurator and explainers.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_api_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/grid-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Grid Search */
        post: operations["research_grid_search_api_research_grid_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/monte-carlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Monte Carlo */
        post: operations["research_monte_carlo_api_research_monte_carlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/robustness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Robustness */
        post: operations["research_robustness_api_research_robustness_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/walk-forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Walk Forward */
        post: operations["research_walk_forward_api_research_walk_forward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Studio Backtest
         * @description Execute and durably record the typed Studio's migrated Research slice.
         */
        post: operations["create_studio_backtest_api_studio_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests/manifested": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Manifested Studio Backtest
         * @description Replay one admitted production dataset without any network dependency.
         */
        post: operations["create_manifested_studio_backtest_api_studio_backtests_manifested_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Studio Backtest */
        get: operations["get_studio_backtest_api_studio_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/canonical-adaptive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Canonical Adaptive
         * @description Present one deterministic legacy-to-canonical adaptive characterization.
         */
        post: operations["canonical_adaptive_api_studio_canonical_adaptive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/catalogs/binance/eur": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binance Eur Catalog
         * @description Return a dated public Testnet/production EUR intersection.
         */
        get: operations["get_binance_eur_catalog_api_studio_catalogs_binance_eur_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Studio Configuration
         * @description Return the canonical defaults for Ticket 02's migrated static Spot slice.
         */
        get: operations["studio_configuration_api_studio_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/binance/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Binance Dataset
         * @description Download and admit only checksum-verified, continuous production history.
         */
        post: operations["import_binance_dataset_api_studio_datasets_binance_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/binance/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Binance Dataset
         * @description Resolve official source identities and sizes before archive download.
         */
        post: operations["preview_binance_dataset_api_studio_datasets_binance_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Studio Dataset */
        get: operations["get_studio_dataset_api_studio_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionLimitsPreview */
        AcquisitionLimitsPreview: {
            /** Max Bytes */
            max_bytes: number;
            /** Max Days */
            max_days: number;
            /** Max Objects */
            max_objects: number;
        };
        /** ArchiveCoverageEvidence */
        ArchiveCoverageEvidence: {
            /** Evidence Urls */
            evidence_urls: string[];
            /**
             * First Date
             * Format: date
             */
            first_date: string;
            /** Intervals */
            intervals: string[];
            /** Known Gap Dates */
            known_gap_dates: string[];
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
        };
        /** ArchiveSourcePreview */
        ArchiveSourcePreview: {
            /** Checksum Url */
            checksum_url: string;
            /** Date */
            date: string;
            /** Estimated Bytes */
            estimated_bytes: number;
            /** Expected Sha256 */
            expected_sha256: string;
            /** Url */
            url: string;
        };
        /** BacktestOptions */
        BacktestOptions: {
            /**
             * Include Trades
             * @default true
             */
            include_trades: boolean;
            /**
             * With Report
             * @default false
             */
            with_report: boolean;
        };
        /**
         * BacktestRequest
         * @description A full declarative backtest spec accepted by the API.
         */
        BacktestRequest: {
            bootstrap?: components["schemas"]["BootstrapSpec"];
            constraints?: components["schemas"]["ConstraintsSpec"];
            data?: components["schemas"]["DataSpec"];
            exchange_rules?: components["schemas"]["ExchangeRulesSpec"];
            fees?: components["schemas"]["FeesSpec"];
            fill?: components["schemas"]["FillSpec"];
            filter?: components["schemas"]["FilterSpec"];
            grid?: components["schemas"]["GridSpec"];
            /**
             * Initial Cash
             * @default 10000
             */
            initial_cash: number;
            margin?: components["schemas"]["MarginSpec"];
            /**
             * Market Type
             * @default spot
             * @enum {string}
             */
            market_type: "spot" | "futures";
            /**
             * N Trials
             * @default 1
             */
            n_trials: number;
            /** Periods Per Year */
            periods_per_year?: number | null;
            sizing?: components["schemas"]["SizingSpec"];
            slippage?: components["schemas"]["SlippageSpec"];
            /**
             * Symbol
             * @default BTCUSDT
             */
            symbol: string;
            /** Venue */
            venue?: string | null;
        };
        /** BinanceDatasetPreview */
        BinanceDatasetPreview: {
            /** Catalog Identity */
            catalog_identity?: string | null;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Estimated Bytes */
            estimated_bytes: number;
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            limits: components["schemas"]["AcquisitionLimitsPreview"];
            /**
             * Market
             * @constant
             */
            market: "spot-production-archive";
            /** Preview Id */
            preview_id: string;
            /** Sources */
            sources: components["schemas"]["ArchiveSourcePreview"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Symbol */
            symbol: string;
            /** Symbol Metadata */
            symbol_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Venue
             * @constant
             */
            venue: "binance";
        };
        /** BinanceDatasetRequest */
        BinanceDatasetRequest: {
            /** Catalog Id */
            catalog_id?: string | null;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Interval
             * @default 1m
             * @constant
             */
            interval: "1m";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Symbol */
            symbol: string;
        };
        /** BinanceEurResearchCatalog */
        BinanceEurResearchCatalog: {
            /** Catalog Id */
            catalog_id: string;
            /** Filters */
            filters: string[];
            /**
             * Quote Asset
             * @constant
             */
            quote_asset: "EUR";
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Sources */
            sources: components["schemas"]["CatalogSourceEvidence"][];
            /** Symbols */
            symbols: components["schemas"]["EurCatalogSymbolEvidence"][];
        };
        /** BootstrapSpec */
        BootstrapSpec: {
            /** Base Fraction */
            base_fraction?: number | null;
            /** Side */
            side?: ("LONG" | "SHORT") | null;
        };
        /** CanonicalActivationGatePresentation */
        CanonicalActivationGatePresentation: {
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "PASSED" | "FAILED" | "BLOCKED";
            /** Reason */
            reason: string;
        };
        /** CanonicalAdaptivePresentation */
        CanonicalAdaptivePresentation: {
            activation: components["schemas"]["CanonicalInitialActivationPresentation"];
            configuration: components["schemas"]["CanonicalConfigurationPresentation"];
            decision: components["schemas"]["CanonicalDecisionPresentation"];
            derived_plan: components["schemas"]["CanonicalDerivedPlanPresentation"] | null;
            legacy_comparison: components["schemas"]["LegacyComparisonPresentation"];
            observation: components["schemas"]["CanonicalObservationPresentation"];
        };
        /** CanonicalAdaptiveRequest */
        CanonicalAdaptiveRequest: {
            /**
             * Activation Price
             * @default 100.00
             */
            activation_price: string;
            /**
             * Bootstrap Complete
             * @default false
             */
            bootstrap_complete: boolean;
            /**
             * Bootstrap Confirmed Base
             * @default 0
             */
            bootstrap_confirmed_base: string;
            /** Bootstrap Evidence Id */
            bootstrap_evidence_id?: string | null;
            /**
             * Complete
             * @default true
             */
            complete: boolean;
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Event Time */
            event_time?: string | null;
            /**
             * Evidence Quality
             * @default ADMITTED
             * @enum {string}
             */
            evidence_quality: "ADMITTED" | "INCOMPLETE" | "STALE" | "GAPPED" | "CONTRADICTORY" | "AMBIGUOUS";
            /**
             * Observed Count
             * @default 24
             */
            observed_count: number;
            /**
             * Reference Price
             * @default 100.00
             */
            reference_price: string;
            /**
             * Sequence End
             * @default 24
             */
            sequence_end: number;
            /**
             * Spacing
             * @default GEOMETRIC
             * @enum {string}
             */
            spacing: "GEOMETRIC" | "ARITHMETIC";
            /**
             * Step Size
             * @default 0.00001
             */
            step_size: string;
            /**
             * Symbol
             * @default BTCEUR
             */
            symbol: string;
            /**
             * Tick Size
             * @default 0.01
             */
            tick_size: string;
            /**
             * Trend
             * @default 0.0000
             */
            trend: string;
            /**
             * Volatility
             * @default 0.0100
             */
            volatility: string;
        };
        /** CanonicalAllocationPresentation */
        CanonicalAllocationPresentation: {
            base_allocation: components["schemas"]["ExactValuePresentation"];
            fee_reserve: components["schemas"]["ExactValuePresentation"];
            quote_allocation: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalBootstrapEvidencePresentation */
        CanonicalBootstrapEvidencePresentation: {
            /** Complete */
            complete: boolean;
            /** Evidence Id */
            evidence_id: string | null;
            net_base_confirmed: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalBootstrapObligationPresentation */
        CanonicalBootstrapObligationPresentation: {
            fee_base_coverage: components["schemas"]["ExactValuePresentation"];
            gross_base_required: components["schemas"]["ExactValuePresentation"];
            net_base_required: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalConfigurationPresentation */
        CanonicalConfigurationPresentation: {
            /** Base Asset */
            base_asset: string;
            /** Configuration Id */
            configuration_id: string;
            /** Execution Policy Id */
            execution_policy_id: string;
            /** Operator Inputs */
            operator_inputs: {
                [key: string]: components["schemas"]["ExactValuePresentation"];
            };
            /** Policy Id */
            policy_id: string;
            /** Quote Asset */
            quote_asset: string;
            /** Risk Profile Id */
            risk_profile_id: string;
            /** Rung Count */
            rung_count: number;
            /** Schema Version */
            schema_version: string;
            /**
             * Spacing
             * @enum {string}
             */
            spacing: "ARITHMETIC" | "GEOMETRIC";
            /** Symbol */
            symbol: string;
        };
        /** CanonicalDecisionPresentation */
        CanonicalDecisionPresentation: {
            /**
             * Adaptation State
             * @enum {string}
             */
            adaptation_state: "RANGE_NORMAL" | "RANGE_HIGH_VOLATILITY" | "TREND_UP" | "TREND_DOWN" | "UNCERTAIN";
            /** Decision Id */
            decision_id: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "SYMMETRIC" | "WIDEN" | "SHIFT_UP" | "REDUCE_ONLY" | "FROZEN";
            /** Permits Exposure Increasing Buy */
            permits_exposure_increasing_buy: boolean;
            /** Reason */
            reason: string;
            requested_bound_shift: components["schemas"]["ExactValuePresentation"] | null;
        };
        /** CanonicalDerivedPlanPresentation */
        CanonicalDerivedPlanPresentation: {
            activation_price: components["schemas"]["ExactValuePresentation"];
            allocation_assumptions: components["schemas"]["CanonicalAllocationPresentation"];
            bootstrap_obligation: components["schemas"]["CanonicalBootstrapObligationPresentation"] | null;
            /** Derivation Causation Id */
            derivation_causation_id: string;
            /** Derivation Semantics */
            derivation_semantics: string;
            /** Epoch Id */
            epoch_id: string;
            lower: components["schemas"]["ExactValuePresentation"];
            maximum_planned_inventory: components["schemas"]["ExactValuePresentation"] | null;
            /** Obligations */
            obligations: components["schemas"]["CanonicalObligationPresentation"][];
            /** Predecessor Epoch Id */
            predecessor_epoch_id: string | null;
            /** Quantized Rungs */
            quantized_rungs: components["schemas"]["CanonicalRungPresentation"][];
            reference_price: components["schemas"]["ExactValuePresentation"];
            /** Schema Version */
            schema_version: string;
            /** Unquantized Rungs */
            unquantized_rungs: components["schemas"]["ExactValuePresentation"][];
            upper: components["schemas"]["ExactValuePresentation"];
            /** Venue Rule Evidence Id */
            venue_rule_evidence_id: string;
        };
        /** CanonicalInitialActivationPresentation */
        CanonicalInitialActivationPresentation: {
            /** Activation Pending */
            activation_pending: boolean;
            /** Automatically Armed */
            automatically_armed: boolean;
            bootstrap_evidence: components["schemas"]["CanonicalBootstrapEvidencePresentation"];
            derived_width: components["schemas"]["ExactValuePresentation"] | null;
            /** Gates */
            gates: components["schemas"]["CanonicalActivationGatePresentation"][];
            /** Ladder Placement Allowed */
            ladder_placement_allowed: boolean;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "REJECTED" | "BOOTSTRAPPING" | "ACTIVE";
            /** Replay Fingerprint */
            replay_fingerprint: string;
            /** Schema Version */
            schema_version: string;
        };
        /** CanonicalObligationPresentation */
        CanonicalObligationPresentation: {
            base_quantity: components["schemas"]["ExactValuePresentation"] | null;
            fixed_quote_principal: components["schemas"]["ExactValuePresentation"];
            /**
             * Role
             * @enum {string}
             */
            role: "BUY" | "SELL";
            /** Rung Index */
            rung_index: number;
        };
        /** CanonicalObservationPresentation */
        CanonicalObservationPresentation: {
            /** Complete */
            complete: boolean;
            /** Confirmation Ids */
            confirmation_ids: string[];
            /**
             * Decision Time
             * Format: date-time
             */
            decision_time: string;
            /** Event Id */
            event_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /** Observation Id */
            observation_id: string;
            /** Prior Decision Id */
            prior_decision_id: string | null;
            /** Quality */
            quality: string;
            reference_price: components["schemas"]["ExactValuePresentation"];
            /** Schema Version */
            schema_version: string;
            /** Source Stream */
            source_stream: string;
            /** Source System */
            source_system: string;
            trend: components["schemas"]["ExactValuePresentation"];
            volatility: components["schemas"]["ExactValuePresentation"];
        };
        /** CanonicalRungPresentation */
        CanonicalRungPresentation: {
            /** Index */
            index: number;
            price: components["schemas"]["ExactValuePresentation"];
            /**
             * Role
             * @enum {string}
             */
            role: "BUY" | "SELL" | "INACTIVE";
        };
        /** CatalogSourceEvidence */
        CatalogSourceEvidence: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "production" | "testnet";
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Url */
            url: string;
        };
        /** ConstraintsSpec */
        ConstraintsSpec: {
            /** Max Base Inventory */
            max_base_inventory?: number | null;
            /** Max Gross Exposure Frac */
            max_gross_exposure_frac?: number | null;
            /** Max Open Orders */
            max_open_orders?: number | null;
            /** Min Notional */
            min_notional?: number | null;
            /** Min Order Qty */
            min_order_qty?: number | null;
        };
        /** DataSpec */
        DataSpec: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** End */
            end?: string | null;
            /** Interval */
            interval?: string | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
            /** Kind */
            kind?: ("synthetic" | "dataframe" | "binance" | "csv" | "manifested_parquet") | null;
            /** Max Candles */
            max_candles?: number | null;
            /** N */
            n?: number | null;
            /** Path */
            path?: string | null;
            /** Records */
            records?: {
                [key: string]: unknown;
            }[] | null;
            /** Regime */
            regime?: ("range" | "trend" | "random") | null;
            /** Seed */
            seed?: number | null;
            /** Sigma */
            sigma?: number | null;
            /** Start */
            start?: string | null;
            /** Start Price */
            start_price?: number | null;
            /** Symbol */
            symbol?: string | null;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Catalog Identity */
            catalog_identity?: string | null;
            /** Coverage */
            coverage: {
                [key: string]: string;
            };
            /** Dataset Id */
            dataset_id: string;
            /**
             * Event Kind
             * @constant
             */
            event_kind: "kline";
            /** Fee Snapshot Id */
            fee_snapshot_id: string | null;
            /**
             * History Environment
             * @constant
             */
            history_environment: "production";
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            /** Manifest Sha256 */
            manifest_sha256: string;
            /**
             * Market
             * @constant
             */
            market: "spot";
            normalization: components["schemas"]["DatasetNormalization"];
            quality: components["schemas"]["DatasetQuality"];
            /** Requested Range */
            requested_range: {
                [key: string]: string;
            };
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Schema Version */
            schema_version: string;
            /** Source Provider */
            source_provider: string;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Symbol */
            symbol: string;
            /** Symbol Metadata */
            symbol_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Timestamp */
            timestamp: {
                [key: string]: unknown;
            };
            /**
             * Venue
             * @constant
             */
            venue: "binance";
            /** Venue Rule Snapshot Id */
            venue_rule_snapshot_id: string | null;
        };
        /** DatasetNormalization */
        DatasetNormalization: {
            /** Candle Sequence Sha256 */
            candle_sequence_sha256: string;
            /**
             * Format
             * @constant
             */
            format: "parquet";
            /** Identity */
            identity: string;
            /** Ordering */
            ordering: string[];
            /** Parent Dataset Id */
            parent_dataset_id: string | null;
            /** Path */
            path: string;
            /** Resampling Rule */
            resampling_rule: string | null;
            /** Rows */
            rows: number;
            /** Schema */
            schema: components["schemas"]["ParquetField"][];
            /** Sha256 */
            sha256: string;
        };
        /** DatasetQuality */
        DatasetQuality: {
            /** Duplicates */
            duplicates: number;
            /** Gaps */
            gaps: number;
            /** Invalid Records */
            invalid_records: number;
            /** Out Of Order */
            out_of_order: number;
            /** Rows */
            rows: number;
        };
        /** EurCatalogSymbolEvidence */
        EurCatalogSymbolEvidence: {
            /** Base Asset */
            base_asset: string;
            coverage: components["schemas"]["ArchiveCoverageEvidence"];
            /** Exchange Filters */
            exchange_filters: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            liquidity: components["schemas"]["LiquiditySelectionEvidence"];
            /** Liquidity Rank */
            liquidity_rank: number;
            /**
             * Quote Asset
             * @constant
             */
            quote_asset: "EUR";
            /**
             * Status
             * @constant
             */
            status: "TRADING";
            /** Symbol */
            symbol: string;
        };
        /** ExactValuePresentation */
        ExactValuePresentation: {
            /** Kind */
            kind: string;
            /** Value */
            value: string;
        };
        /** ExchangeRulesSpec */
        ExchangeRulesSpec: {
            /** Enabled */
            enabled?: boolean | null;
            /** Min Notional */
            min_notional?: number | null;
            /** Min Qty */
            min_qty?: number | null;
            /** Step Size */
            step_size?: number | null;
            /** Tick Size */
            tick_size?: number | null;
        };
        /** FeesSpec */
        FeesSpec: {
            /** Maker */
            maker?: number | null;
            /** Taker */
            taker?: number | null;
        };
        /** FillSpec */
        FillSpec: {
            /** Fill Gaps At Open */
            fill_gaps_at_open?: boolean | null;
            /** Fill On Touch */
            fill_on_touch?: boolean | null;
            /** Mode */
            mode?: ("optimistic" | "conservative") | null;
            /** Participation */
            participation?: number | null;
        };
        /** FilterSpec */
        FilterSpec: {
            /** Adx Threshold */
            adx_threshold?: number | null;
            /** Kind */
            kind?: ("none" | "trend" | "regime" | "rsi") | null;
            /** Overbought */
            overbought?: number | null;
            /** Oversold */
            oversold?: number | null;
        };
        /**
         * GridPreviewBody
         * @description Lightweight request to compute grid rung prices for the live preview.
         */
        GridPreviewBody: {
            spec?: components["schemas"]["BacktestRequest"];
        };
        /** GridSearchBody */
        GridSearchBody: {
            base?: components["schemas"]["BacktestRequest"];
            /**
             * Maximize
             * @default true
             */
            maximize: boolean;
            /**
             * Objective
             * @default deflated_sharpe
             */
            objective: string;
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
            /** Top K */
            top_k?: number | null;
        };
        /** GridSpec */
        GridSpec: {
            /** Adaptive */
            adaptive?: boolean | null;
            /** Atr Mult */
            atr_mult?: number | null;
            /** Atr Period */
            atr_period?: number | null;
            /** Direction */
            direction?: ("neutral" | "long" | "short") | null;
            /** Levels */
            levels?: number | null;
            /** Lookback */
            lookback?: number | null;
            /** Lower */
            lower?: number | null;
            /** Recenter Drift Frac */
            recenter_drift_frac?: number | null;
            /** Spacing */
            spacing?: ("arithmetic" | "geometric" | "atr") | null;
            /** Stop Loss Frac */
            stop_loss_frac?: number | null;
            /** Take Profit Frac */
            take_profit_frac?: number | null;
            /** Upper */
            upper?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportDatasetBody */
        ImportDatasetBody: {
            /** Preview Id */
            preview_id: string;
        };
        /** LegacyComparisonPresentation */
        LegacyComparisonPresentation: {
            /** Bounded Bars */
            bounded_bars: number;
            /** Cancelled Orders */
            cancelled_orders: number;
            /** Effective Atr Multiplier */
            effective_atr_multiplier: string;
            /** Legacy Adaptive */
            legacy_adaptive: boolean;
            /** Legacy Spacing */
            legacy_spacing: string;
            /** Semantic Differences */
            semantic_differences: string[];
        };
        /** LiquiditySelectionEvidence */
        LiquiditySelectionEvidence: {
            /** Annualized Realized Volatility */
            annualized_realized_volatility: string;
            /** Current Spread Bps */
            current_spread_bps: string;
            /** Current Trade Count */
            current_trade_count: number;
            /** Kline Payload Sha256 */
            kline_payload_sha256: string;
            /** Kline Source Url */
            kline_source_url: string;
            /** Median Daily Quote Volume */
            median_daily_quote_volume: string;
            /** Median Daily Trade Count */
            median_daily_trade_count: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Observed Days */
            observed_days: number;
            /**
             * Observed End Date
             * Format: date
             */
            observed_end_date: string;
            /**
             * Observed Start Date
             * Format: date
             */
            observed_start_date: string;
            /** Ticker Payload Sha256 */
            ticker_payload_sha256: string;
            /** Ticker Source Url */
            ticker_source_url: string;
        };
        /** ManifestedBacktestBody */
        ManifestedBacktestBody: {
            /** Dataset Id */
            dataset_id: string;
            options?: components["schemas"]["BacktestOptions"];
            spec: components["schemas"]["BacktestRequest"];
        };
        /** MarginSpec */
        MarginSpec: {
            /** Allow Short */
            allow_short?: boolean | null;
            /** Leverage */
            leverage?: number | null;
            /** Liquidation Fee Frac */
            liquidation_fee_frac?: number | null;
            /** Maintenance Margin Frac */
            maintenance_margin_frac?: number | null;
        };
        /** MonteCarloBody */
        MonteCarloBody: {
            base?: components["schemas"]["BacktestRequest"];
            /**
             * Method
             * @default trades
             * @enum {string}
             */
            method: "trades" | "returns";
            /**
             * N Sims
             * @default 2000
             */
            n_sims: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** ParquetField */
        ParquetField: {
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /** Type */
            type: string;
        };
        /** ProductionDatasetProvenance */
        ProductionDatasetProvenance: {
            /** Backtest Fingerprint */
            backtest_fingerprint: string;
            /** Candle Sequence Sha256 */
            candle_sequence_sha256: string;
            /** Catalog Identity */
            catalog_identity?: string | null;
            /** Dataset Id */
            dataset_id: string;
            /**
             * History Environment
             * @constant
             */
            history_environment: "production";
            /**
             * Interval
             * @constant
             */
            interval: "1m";
            /** Manifest Identity */
            manifest_identity: string;
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Quote Asset */
            quote_asset?: string | null;
            /**
             * Requested End
             * Format: date-time
             */
            requested_end: string;
            /**
             * Requested Start
             * Format: date-time
             */
            requested_start: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Provider */
            source_provider: string;
            /** Source Urls */
            source_urls: string[];
            /** Symbol */
            symbol: string;
            /**
             * Testnet History Used
             * @constant
             */
            testnet_history_used: false;
        };
        /** RobustnessBody */
        RobustnessBody: {
            base?: components["schemas"]["BacktestRequest"];
            /**
             * Mc Sims
             * @default 800
             */
            mc_sims: number;
            /**
             * N Splits
             * @default 3
             */
            n_splits: number;
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
        };
        /** RunBacktestBody */
        RunBacktestBody: {
            options?: components["schemas"]["BacktestOptions"];
            spec?: components["schemas"]["BacktestRequest"];
        };
        /** SizingSpec */
        SizingSpec: {
            /** Martingale Factor */
            martingale_factor?: number | null;
            /** Max Martingale Steps */
            max_martingale_steps?: number | null;
            /** Mode */
            mode?: ("fixed_quote" | "fixed_base" | "percent_equity" | "martingale") | null;
            /** Value */
            value?: number | null;
        };
        /** SlippageSpec */
        SlippageSpec: {
            /** Impact Frac */
            impact_frac?: number | null;
            /** Spread Frac */
            spread_frac?: number | null;
        };
        /** StudioBacktestResult */
        StudioBacktestResult: {
            /** Bars */
            bars: number;
            /** Fees Paid */
            fees_paid: number;
            /** Final Equity */
            final_equity: number;
            /** Initial Cash */
            initial_cash: number;
            metrics: components["schemas"]["StudioMetrics"];
            /** Symbol */
            symbol: string;
            /** Trades */
            trades: {
                [key: string]: unknown;
            }[];
            verdict: components["schemas"]["StudioVerdict"];
        } & {
            [key: string]: unknown;
        };
        /** StudioBacktestRun */
        StudioBacktestRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            primary_result: components["schemas"]["StudioPrimaryResult"];
            provenance?: components["schemas"]["ProductionDatasetProvenance"] | null;
            result: components["schemas"]["StudioBacktestResult"];
            /** Specification */
            specification: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @constant
             */
            status: "completed";
        };
        /** StudioConfiguration */
        StudioConfiguration: {
            /** Data Regimes */
            data_regimes: ("range" | "trend" | "random")[];
            default_spec: components["schemas"]["BacktestRequest"];
            /** Spacing */
            spacing: ("geometric" | "arithmetic")[];
        };
        /** StudioMetrics */
        StudioMetrics: {
            /** Max Drawdown */
            max_drawdown: number;
            /** N Trades */
            n_trades: number;
            /** Total Return */
            total_return: number;
            /** Win Rate */
            win_rate: number | null;
        } & {
            [key: string]: unknown;
        };
        /** StudioPrimaryResult */
        StudioPrimaryResult: {
            /** Completed Trades */
            completed_trades: number;
            /** Fees Paid */
            fees_paid: number;
            /** Final Equity */
            final_equity: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Net Return */
            net_return: number;
            /** Verdict */
            verdict: string;
        };
        /** StudioVerdict */
        StudioVerdict: {
            /** Label */
            label: string;
            /** Max Score */
            max_score: number;
            /** Score */
            score: number;
            /**
             * Tone
             * @enum {string}
             */
            tone: "good" | "warn" | "bad";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalkForwardBody */
        WalkForwardBody: {
            base?: components["schemas"]["BacktestRequest"];
            /**
             * N Splits
             * @default 4
             */
            n_splits: number;
            /**
             * Objective
             * @default deflated_sharpe
             */
            objective: string;
            /** Space */
            space?: {
                [key: string]: unknown[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtest_api_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grid_preview_api_grid_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridPreviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    report_api_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_grid_search_api_research_grid_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridSearchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_monte_carlo_api_research_monte_carlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_robustness_api_research_robustness_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobustnessBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_walk_forward_api_research_walk_forward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalkForwardBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_studio_backtest_api_studio_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manifested_studio_backtest_api_studio_backtests_manifested_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestedBacktestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_studio_backtest_api_studio_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioBacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    canonical_adaptive_api_studio_canonical_adaptive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanonicalAdaptiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalAdaptivePresentation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binance_eur_catalog_api_studio_catalogs_binance_eur_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceEurResearchCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    studio_configuration_api_studio_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioConfiguration"];
                };
            };
        };
    };
    import_binance_dataset_api_studio_datasets_binance_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportDatasetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_binance_dataset_api_studio_datasets_binance_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinanceDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceDatasetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_studio_dataset_api_studio_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
